Update

diff --git a/.config/rofi/bin/auto_google_search b/.config/rofi/bin/auto_google_search
--- a/.config/rofi/bin/auto_google_search
+++ b/.config/rofi/bin/auto_google_search
@@ -1,10 +1,41 @@
 #!/bin/bash
 
+browser=brave
+
+autoGoogleSearch(){
 # Get content from clipboard
 clipboard_content=$(xclip -o -selection clipboard)
 
 # Encode clipboard content for URL
 encoded_content=$(echo "$clipboard_content" | sed 's/ /+/g')
 
-# Open Brave browser and search YouTube
-brave "https://www.google.com/search?q=$encoded_content"
+# Open Brave browser and search google
+$browser "https://www.google.com/search?q=$encoded_content"
+}
+
+inputGoogleSearch(){
+  query=$(rofi -dmenu -p "  Google")
+  if [[ -z "$query" ]]; then
+    sh ~/.config/rofi/bin/rofi-quicklink
+    exit 0
+  else
+    notify-send "Searching $query" "Using $search_engine" -t 2200
+    echo "$query" | printf %s "$(< /dev/stdin)" | xclip -sel c
+    echo "$query"  # Output the query as the return value of the function
+  fi
+  $browser "https://www.google.com/search?q=$query" &
+}
+
+# Check for the provided argument
+case "$1" in
+  autoGoogleSearch)
+    autoGoogleSearch
+    ;;
+  userGoogleSearch)
+    inputGoogleSearch
+    ;;
+  *)
+    echo "Usage: $0 {autoGoogleSearch|userGoogleSearch}"
+    exit 1
+    ;;
+esac
diff --git a/.config/rofi/bin/auto_youtube_search b/.config/rofi/bin/auto_youtube_search
--- a/.config/rofi/bin/auto_youtube_search
+++ b/.config/rofi/bin/auto_youtube_search
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+browser=brave
+
+autoYoutubeSearch(){
 # Get content from clipboard
 clipboard_content=$(xclip -o -selection clipboard)
 
@@ -7,4 +10,32 @@ clipboard_content=$(xclip -o -selection clipboard)
 encoded_content=$(echo "$clipboard_content" | sed 's/ /+/g')
 
 # Open Brave browser and search YouTube
-brave "https://www.youtube.com/results?search_query=$encoded_content"
+$browser "https://www.youtube.com/results?search_query=$encoded_content"
+}
+
+inputYoutbeSearch(){
+  query=$(rofi -dmenu -p "  YouTube")
+  if [[ -z "$query" ]]; then
+    sh ~/.config/rofi/bin/rofi-quicklink
+    exit 0
+  else
+    notify-send "Searching $query" "Using $search_engine" -t 2200
+    echo "$query" | printf %s "$(< /dev/stdin)" | xclip -sel c
+    echo "$query"  # Output the query as the return value of the function
+  fi
+  $browser "https://youtube.com/results?search_query=$query" &
+}
+
+# Check for the provided argument
+case "$1" in
+  autoYoutubeSearch)
+    autoYoutubeSearch
+    ;;
+  userYoutubeSearch)
+    inputYoutbeSearch
+    ;;
+  *)
+    echo "Usage: $0 {autoYoutubeSearch|userYoutubeSearch}"
+    exit 1
+    ;;
+esac
